insert into Acao (nomeEmpresa, valor) values ('A Suprema', 10.00);
insert into Acao (nomeEmpresa, valor) values ('NOVIMODAS', 100.00);
insert into Acao (nomeEmpresa, valor) values ('GBarbosa', 20.00);
insert into Acao (nomeEmpresa, valor) values ('Gerdau', 30.00);
insert into Acao (nomeEmpresa, valor) values ('COSIL', 60.00);
insert into Acao (nomeEmpresa, valor) values ('Bompreco', 40.00);
insert into Acao (nomeEmpresa, valor) values ('PNEUSERVICE', 90.00);
insert into Acao (nomeEmpresa, valor) values ('Petrobras', 50.00);
insert into Acao (nomeEmpresa, valor) values ('CICLOPECAS', 70.00);
insert into Acao (nomeEmpresa, valor) values ('PANIFICACAO GARCA', 80.00);
